# Generated by Django 3.1 on 2020-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_demo_ui_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoapppage',
            name='page_background_color',
            field=models.CharField(choices=[('transparent', 'transparent'), ('yellow', 'yellow'), ('red', 'red')], default='transparent', help_text='Allows configuring the background color of the page.', max_length=11),
        ),
    ]
