# Generated by Django 3.1 on 2020-09-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0001_initial'),
        ('emp_demo_ui_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoapppage',
            name='demo_datapoint',
            field=models.ForeignKey(blank=True, help_text='A simple example how to use a Datapoint in a model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_main.datapoint'),
        ),
    ]
