# Generated by Django 3.1 on 2020-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_demo_ui_app', '0002_demoapppage_demo_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoapppage',
            name='page_has_detail',
            field=models.BooleanField(default=False, help_text='Page displays datapoint detail page if True.'),
        ),
    ]
