stages:
  - build
  - test

variables:
  DOCKER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG

build:
  stage: build
  image: $CI_REGISTRY/dwo/docker-build-image-cache/docker:20.10.14
  services:
    - name: $CI_REGISTRY/dwo/docker-build-image-cache/docker:20.10.14-dind
      alias: dockerhost
  variables:
    # These are used by the docker image?
    DOCKER_HOST: tcp://dockerhost:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo Building docker image $DOCKER_IMAGE
    - docker build ./source -t $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE

test:
  stage: test
  image: $CI_REGISTRY/dwo/docker-build-image-cache/docker:20.10.14
  services:
    - name: $CI_REGISTRY/dwo/docker-build-image-cache/docker:20.10.14-dind
      alias: dockerhost
  variables:
    # These are used by the docker image?
    DOCKER_HOST: tcp://dockerhost:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker run -t --rm --entrypoint=/opt/conda/bin/pytest $DOCKER_IMAGE /source/emp/
    - docker image rm $DOCKER_IMAGE
