version: '3'

# Use these volumes for development only.
volumes:
    emp-devl-db-pgdata:
        name: emp-devl-db-pgdata

services:
    emp-devl:
        container_name: emp-devl
        build:
            context: ./source
        restart: unless-stopped
        init: true  # Faster shutdown.
        tty: true  # This must be set to colorize output.
        volumes:
            - ./source/emp/:/source/emp/
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        ports:
            - 8080:8080
        environment:
            - LOGLEVEL=INFO
            - DJANGO_DEBUG=TRUE
            - DJANGO_ADMINS=
            - DJANGO_SECRET_KEY=
            - DJANGO_ALLOWED_HOSTS=
            - DJANGO_SUPERUSER_USERNAME=emp
            - DJANGO_SUPERUSER_PASSWORD=emp
            - DJANGO_SUPERUSER_EMAIL=emp@example.com
            - EMPDB_HOST=django-api-devl-db
            - EMPDB_PORT=5432
            - EMPDB_USER=emp
            - EMPDB_PASSWORD=emp
            - EMPDB_DBNAME=emp
            - N_WORKER_PROCESSES=1
            
    emp-devl-db:
        container_name: emp-devl-db
        image: timescale/timescaledb:2.4.1-pg13
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - emp-devl-db-pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=emp
            - POSTGRES_PASSWORD=emp
            - POSTGRES_DB=emp
