version: '3'

# Use these volumes for development only.
volumes:
    emp-devl-db-pgdata:
        name: emp-devl-db-pgdata

services:
    emp-devl:
        container_name: emp-devl
        build:
            context: ./source/emp
        restart: unless-stopped
        init: true  # Faster shutdown.
        tty: true  # This must be set to colorize output.
        volumes:
            - ./source/emp/:/source/emp/
            # Activate this volume if you develop on energy_service_generics in parallel. 
            - ../energy_service_generics/source/esg/:/opt/conda/lib/python3.8/site-packages/esg/
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        ports:
            - 8080:8080
        environment:
            - LOGLEVEL=INFO
            - DJANGO_DEBUG=TRUE
            - DJANGO_ADMINS=
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_ALLOWED_HOSTS=["emp-devl","localhost"]
            - DJANGO_SUPERUSER_USERNAME=emp
            - DJANGO_SUPERUSER_PASSWORD=emp
            - DJANGO_SUPERUSER_EMAIL=emp@example.com
            # - EMPDB_HOST=emp-devl-db
            - EMPDB_PORT=5432
            - EMPDB_USER=emp
            - EMPDB_PASSWORD=emp
            - EMPDB_DBNAME=emp
            - N_WORKER_PROCESSES=1

    emp-devl-db:
        container_name: emp-devl-db
        image: timescale/timescaledb:2.4.1-pg13
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - emp-devl-db-pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=emp
            - POSTGRES_PASSWORD=emp
            - POSTGRES_DB=emp
            
    emp-devl-demp-dp-interface:
        container_name: emp-devl-demp-dp-interface
        build:
            context: ./source/demo_datapoint_interface
        restart: unless-stopped
        init: true  # Faster shutdown.
        tty: true  # This must be set to colorize output.
        volumes:
            - ./source/demo_datapoint_interface/:/source/demo_datapoint_interface/
            # Activate this volume if you develop on energy_service_generics in parallel. 
            - ../energy_service_generics/source/esg/:/opt/conda/lib/python3.8/site-packages/esg/
        environment:
            - EMP_API_URL=http://emp-devl:8080/api
