"""
Django settings for emp_main project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import json
import random
import string
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    # This generates a new random key every time we start the application or
    # run anything from manage.py. This also invalidates all cookies which
    # makes users login again. Thus, it is a good idea to fix the key in
    # production.
    # However, this only works if we have only a single worker. If there are
    # more then one, each will get a dedicated SECRET_KEY which will cause
    # permanent suspicious session warnings.
    if int(os.getenv("N_WORKER_PROCESSES") or 1) == 1:
        SECRET_KEY = "".join(
            random.choice(string.ascii_letters) for i in range(64)
        )
    else:
        raise ValueError(
            "DJANGO_SECRET_KEY must be set explicitly if "
            "N_WORKER_PROCESSES > 1."
        )


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if (os.getenv("DJANGO_DEBUG") or "FALSE").lower() == "true":
    DEBUG = True

ALLOWED_HOSTS = json.loads(os.getenv("DJANGO_ALLOWED_HOSTS") or '["localhost"]')
if os.getenv("DJANGO_ADMINS"):
    ADMINS = json.loads(os.getenv("DJANGO_ADMINS"))

# Application definition
INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "guardian",
    "ninja",
    "emp_main.apps.EmpMainConfig",
    "emp_demo_ui_app.apps.EmpDemoUiAppConfig",
    "emp_django_authenticator.apps.EmpDjangoAuthenticatorConfig",
    "emp_energy_flow.apps.EmpEnergyFlow",
    "emp_external_page.apps.EmpExternalPageAppConfig",
    # Uncomment to activate the emp_evaluation_system app.
    # Note that additional depedencies must be installed too.
    # "emp_evaluation_system.apps.EmpEvaluationSystemConfig",
    # "nested_admin",
    # "multiselectfield",
] + json.loads(os.getenv("DJANGO_ADDITIONAL_INSTALLED_APPS") or "[]")

# Define all installed apps which extend the EMP functionality.
# This is used to automatically wire up the urls to these apps and to
# automatically generate the user permissions for these apps.
# This process expects that each app holds a apps.py and urls.py file following
# the conventions shown in emp_demo_ui_app.
EMP_APPS = [
    "emp_demo_ui_app",
    "emp_django_authenticator",
    "emp_energy_flow",
    "emp_external_page",
    # "emp_evaluation_system",
] + json.loads(os.getenv("EMP_ADDITIONAL_APPS") or "[]")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # this is django default.
    "guardian.backends.ObjectPermissionBackend",  # required for guardian.
)

ROOT_URLCONF = "emp_main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "emp_main.wsgi.application"
ASGI_APPLICATION = "emp_main.asgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
if os.getenv("EMPDB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "timescale.db.backends.postgresql",
            "HOST": os.getenv("EMPDB_HOST"),
            "PORT": int(os.getenv("EMPDB_PORT") or 5432),
            "USER": os.getenv("EMPDB_USER") or "emp",
            "PASSWORD": os.getenv("EMPDB_PASSWORD") or "emp",
            "NAME": os.getenv("EMPDB_DBNAME") or "emp",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR.parent / "db.sqlite3",
        }
    }

# Configure the Channel Layer used to push updates to websockets. See:
# https://channels.readthedocs.io/en/stable/topics/channel_layers.html
if os.getenv("CHANNELS_REDIS_HOST"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    (
                        os.getenv("CHANNELS_REDIS_HOST"),
                        int(os.getenv("CHANNELS_REDIS_PORT") or 6379),
                    )
                ],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }

# This is just here to silence some warnings and make explicit what
# django < 3.2 has always done. See:
# https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-DEFAULT_AUTO_FIELD
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Logging inspired by suggestions in practical django book.
# This configures one explicit logger per app, as this allows us
# to identify the source of a log message easily.
log_level = os.getenv("LOGLEVEL") or "INFO"

loggers = {}
# Explicitly add emp_main, as log messages from it won't be displayed else.
for emp_app in EMP_APPS + ["emp_main"]:
    loggers[emp_app] = {
        "handlers": ["console", "prometheus"],
        "level": log_level,
        "propagate": True,
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s-%(name)s-%(levelname)s: %(message)s"}
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "emp_main.loggers.StreamHandlerPlusIPs",
            "formatter": "simple",
        },
        "prometheus": {
            "level": "DEBUG",
            "class": "emp_main.loggers.PrometheusHandler",
        },
    },
    "loggers": loggers,
    "root": {"handlers": ["console", "prometheus"], "level": log_level},
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
# fmt: off
AUTH_PASSWORD_VALIDATORS = [
    # NOQA here as breaking these lines won't improve readability.
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # NOQA
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # NOQA
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # NOQA
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # NOQA
    },
]
# fmt: on

# The default value (1000) prevents us from deleting larger number of items
# with Django Admin. See also:
# https://docs.djangoproject.com/en/3.1/ref/settings/#data-upload-max-number-fields
DATA_UPLOAD_MAX_NUMBER_FIELDS = None

# Don't attempt to auto correct URLs. This will cause nasty 500 errors
# on put endpoints, while the actual problem is a 404.
APPEND_SLASH = False

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Root path aka. base url. In theory django doesn't need to know the
# root path and works as expected behind a reverse proxy. Here the
# main issue is that we use a lot of absolute URLs, which need to be
# fixed manually.
# **NOTE**: ROOT_PATH must be without a leading slash but with a trailing
# slash if not empty, e.g. `emp/`
ROOT_PATH = os.getenv("ROOT_PATH") or ""

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = BASE_DIR.parent / "static"
STATIC_URL = "/" + ROOT_PATH + "static/"

# Don't place media files in source folder but next to it.
MEDIA_ROOT = BASE_DIR.parent / "media"
MEDIA_URL = "/" + ROOT_PATH + "media/"

# Finally some security related stuff, that is only relevant for production
# where we don't offer a plain HTTP page. The first two are suggested by
# Django's deployment checklist, the remaining by the check --deploy result.
if (os.getenv("HTTPS_ONLY") or "FALSE").lower() == "true":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Required to load Grafana dashboards from suburl.
X_FRAME_OPTIONS = "SAMEORIGIN"

# ------------------------------------------------------------------------------
# Here the EMP specific settings.
# ------------------------------------------------------------------------------

# The string for the <title> tag.
PAGE_TITLE = os.getenv("EMP_PAGE_TITLE") or "EMP Demo"

# The path to the manifest.json file within the static files.
MANIFEST_JSON_STATIC = (
    os.getenv("EMP_MANIFEST_JSON_STATIC") or "emp-main/manifest.json"
)

# The path to the favicon.ico file within the static files.
FAVICON_ICO_STATIC = (
    os.getenv("EMP_FAVICON_ICO_STATIC") or "emp-main/icons/favicon.ico"
)

# The path to the logo displayed in the left corner of the top nav bar,
# as usual within static files.
TOPBAR_LOGO_STATIC = (
    os.getenv("EMP_TOPBAR_LOGO_STATIC") or "emp-main/icons/title-logo.png"
)

# Strings to display in the top navbar.
TOPBAR_NAME_SHORT = os.getenv("EMP_TOPBAR_NAME_SHORT") or "EMP"
TOPBAR_NAME_LONG = (
    os.getenv("EMP_TOPBAR_NAME_LONG") or "Energy Management Panel"
)

# A list of URLS that are excluded from permission checking, i.e. that can be
# accessed by any user at all times. This is required to allow access to pages
# generic pages like login/logout or the home page, if those are not part of
# an UI app.
URLS_PERMISSION_WHITELIST = json.loads(
    os.getenv("EMP_URLS_PERMISSION_WHITELIST")
    or json.dumps(
        [
            "/" + ROOT_PATH + "welcome/",
            "/" + ROOT_PATH + "auth/login/",
            "/" + ROOT_PATH + "auth/logout/",
        ]
    )
)

# Users will be redirected to this page if visiting the sites root.
HOME_PAGE_URL = os.getenv("EMP_HOME_PAGE_URL") or "/" + ROOT_PATH + "welcome/"

# Defines the URLS that are placed in the login/logout buttons in the
# EMPBaseView. Use ?next= to redirect after login/logout.
LOGIN_PAGE_URL = (
    os.getenv("EMP_LOGIN_PAGE_URL")
    or "/" + ROOT_PATH + "auth/login/?next=%s" % HOME_PAGE_URL
)
LOGOUT_PAGE_URL = (
    os.getenv("EMP_LOGOUT_PAGE_URL")
    or "/" + ROOT_PATH + "auth/logout/?next=%s" % HOME_PAGE_URL
)

# EPM evaluation page update interval in milliseconds
# EMP_EVALUATION_PAGE_UPDATE_INTERVAL = 60000
