# Generated by Django 3.2.13 on 2022-05-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the group as displayed in the nav bar. Should not exceed 20 chars, as the string will be wider then the available space in the navbar.', max_length=20)),
                ('slug', models.SlugField(help_text='The name of the group used in the URL of it. Must be unique as two group of this app cannot have the same url.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the page as displayed in the nav bar. Should not exceed 18 chars, as the string will be wider then the available space in the navbar.', max_length=18)),
                ('slug', models.SlugField(help_text='The name of the page used in the URL of it. Must be unique as two pages of this app cannot have the same url.', unique=True)),
                ('src', models.URLField(help_text='The URL of the external page that should be loaded in the frame.', max_length=1024)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_external_page.externalpagegroup')),
            ],
        ),
    ]
