# Generated by Django 3.2.12 on 2022-06-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0001_initial'),
        ('emp_external_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpage',
            name='product_for_run',
            field=models.ForeignKey(blank=True, help_text='Optionally specify a product here, if you do so will append each Grafana URL with the latest product run for this product. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_main.product'),
        ),
    ]
