# Generated by Django 3.2.13 on 2022-04-22 08:47

from django.db import migrations, models
import esg.models.datapoint


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='data_format',
            field=models.CharField(choices=[('Generic Numeric', 'Generic Numeric'), ('Continuous Numeric', 'Continuous Numeric'), ('Discrete Numeric', 'Discrete Numeric'), ('Generic Text', 'Generic Text'), ('Discrete Text', 'Discrete Text'), ('Boolean', 'Boolean'), ('Unknown', 'Unknown')], default=esg.models.datapoint.DatapointDataFormat['unknown'], help_text='Format of the datapoint value. Additionally defines which metadata is available for it. See Enum docs for details.', max_length=18),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.CharField(choices=[('Sensor', 'Sensor'), ('Actuator', 'Actuator')], default=None, help_text='Datapoints can either be of type `sensor` (readable) or `actuator` (writeable).', max_length=8),
        ),
    ]
