# Generated by Django 3.2.13 on 2022-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0002_auto_20220422_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='short_name',
            field=models.TextField(blank=True, default=None, help_text='A short name to identify the datapoint.', null=True),
        ),
    ]
