# Generated by Django 3.1 on 2020-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='short_name',
            field=models.SlugField(default=None, help_text='A short name to identify the datapoint.', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='external_id',
            field=models.TextField(blank=True, help_text="This id used if Datapoints data is pushed in from an external tool (e.g. BEMCom) that maintains it's own list datapoint metadata. This field allows matching the ids of the external tools with the database table of the EMP, effectively allowing the EMP to store Datapoints additionally to what is pushed from the external tool, e.g. for mock (fake) values.", null=True, unique=True),
        ),
    ]
