# Generated by Django 3.1.3 on 2020-12-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0002_auto_20201014_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='external_id',
            new_name='origin_id',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='origin_description',
            field=models.TextField(blank=True, help_text='A human readable description of the datapoint targeted on users of the API wihtout knowledge about connector details.This is the description provided by the extenral tool.'),
        ),
    ]
