# Generated by Django 3.1.3 on 2020-12-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_main', '0003_auto_20201221_1329'),
        ('emp_history_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapointvalue',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The field that stores the timestamp of value msg as datetime.', null=True),
        ),
        migrations.CreateModel(
            name='DatapointSetpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField(blank=True, default=None, help_text='The setpoint field in datapoint setpoint msg.', null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=None, help_text='The field that stores the timestamp of setpoint msg as datetime.', null=True)),
                ('datapoint', models.ForeignKey(help_text='The datapoint that the setpoint message belongs to.', on_delete=django.db.models.deletion.CASCADE, to='emp_main.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='DatapointSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField(blank=True, default=None, help_text='The schedule field in datapoint schedule msg.', null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=None, help_text='The field that stores the timestamp of schedule msg as datetime.', null=True)),
                ('datapoint', models.ForeignKey(help_text='The datapoint that the schedule message belongs to.', on_delete=django.db.models.deletion.CASCADE, to='emp_main.datapoint')),
            ],
        ),
    ]
