# Generated by Django 3.2.12 on 2022-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_energy_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyflow',
            name='name',
            field=models.CharField(help_text='The name of the Energy Flow, will be displayed in the Nav menu.', max_length=18),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(help_text='The Name of the Widget displayed in the header of the card. ', max_length=100),
        ),
    ]
