# Generated by Django 3.2.13 on 2022-04-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAppPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='The name of the page as displayed in the nav bar. Should not exceed 18 chars, as the string will be wider then the available space in the navbar.', max_length=18)),
                ('page_slug', models.SlugField(help_text='The name of the page used in the URL of it. Must be unique as two pages of this app cannot have the same url.', unique=True)),
                ('page_content', models.TextField(help_text="This is an example for some Content of the page that can be configured dynamically, i.e. by using Django's admin.")),
                ('page_background_color', models.CharField(choices=[('transparent', 'transparent'), ('yellow', 'yellow'), ('red', 'red')], default='transparent', help_text='Allows configuring the background color of the page.', max_length=11)),
                ('page_has_detail', models.BooleanField(default=False, help_text='Page displays datapoint detail page if True.')),
                ('demo_datapoint', models.ForeignKey(blank=True, help_text='A simple example how to use a Datapoint in a model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_main.datapoint')),
            ],
        ),
    ]
