# Generated by Django 3.1 on 2020-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_demo_ui_app', '0003_demoapppage_page_has_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoapppage',
            name='page_LukasTestField',
            field=models.TextField(default='Test', help_text='Wow this is an amazing test text field'),
            preserve_default=False,
        ),
    ]
