# Generated by Django 3.1.14 on 2022-04-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_demo_ui_app', '0004_demoapppage_page_lukastestfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoapppage',
            name='page_LukasTestField',
        ),
    ]
