# Generated by Django 3.1.5 on 2021-05-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_main', '0004_auto_20210407_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the page (i.e. location) as displayed in the navbar, e.g. 3.1.07. Should not exceed 18 chars, as the string will be wider then the available space in the navbar.', max_length=18, unique=True)),
                ('slug', models.SlugField(help_text='The name of the page used in the URL of it. Must be unique as two pages of this app cannot have the same URL.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('climate', 'Climate'), ('temperature_control', 'Temperature Control'), ('occupancy', 'Occupancy')], default='climate', max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyWidgetAddition',
            fields=[
                ('widget', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emp_locations.widget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureControlWidgetAddition',
            fields=[
                ('widget', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emp_locations.widget')),
                ('temperature_measured', models.ForeignKey(default=None, help_text='The datapoint holding the temperature value of the location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emp_main.datapoint')),
                ('temperature_setpoint', models.ForeignKey(default=None, help_text='The datapoint used for sending the setpoint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emp_main.datapoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClimateWidgetAddition',
            fields=[
                ('widget', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emp_locations.widget')),
                ('humidity', models.ForeignKey(default=None, help_text='The datapoint holding the humidity value of the location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emp_main.datapoint')),
                ('temperature', models.ForeignKey(default=None, help_text='The datapoint holding the temperature value of the location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emp_main.datapoint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
